### ISSUE TITLE
Snakemake_dir not updated when running app in workflow mode

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#101]
`config["snakemake_dir"]` is automatically set to whatever path is passed into `SnakeBidsApp` by the user. The presents a problem in workflow mode, as `config["snakemake_dir"]` is (I think) typically used to get properly resolved paths to the Snakemake app directory. Since the Snakemake app is being replicated in workflow mode, the path in `"snakemake_dir"` should be updated to the child app. Otherwise the child maintains an unhealthy dependence on its parent.

**Comment by akhanf** [comment]
Yeah I noticed this recently too. Only thing I can think of in the short-term to set that variable is to modify generate_inputs to return it. 

I am thinking a better long-term solution is to use a get_source_path function, in draft PR #102 for now, to allow users to get paths relative to the snakefile or rule file they are in. I originally thought snakemake's workflow.source_path function could do this, but it doesn't handle paths to directories, and caches the file locally (which @tkkuehn mentioned caused some issues).  

I've tried this out and seems to work fine, but would need to add some more test cases if we go ahead with it.
