### ISSUE TITLE
Error if no filters are included

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#110]
`_read_lists_from_bids` in `bids.py` takes for granted that each entry in `pybids_inputs` will have a `filters` attribute. You thus get a `KeyError` if you don't have any filters. The same applies to `wildcards`.

I would say having no `filters` should definitely be defined. One could also argue that having no `wildcards` should also be defined behaviour, albeit of suspect usefulness. Unless you were dealing with just a single file, it would almost currently trigger the warning that `"More than one snakemake file name for &s..."`.

If we do stick with disallowing absence of any `wildcards`, we should have a specific check an a nicer warning.

Thoughts? @akhanf @kaitj @tkkuehn

**Comment by tkkuehn** [comment]
I agree that we should support workflow configs with no wildcards and/or no filters defined.

**Comment by kaitj** [comment]
Agree about supporting workflow configs with no defined filters. I think for completeness, we should also support no wildcards.
