### ISSUE TITLE
Config file inside source workflow is being modified during execution, even with bids-app mode

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#113]
Not sure when this was introduced, but this is causing a major problem for containerized deployment (eg of hippunfold) since the config file in the installed workflow is read-only. Just realized it is happening, so haven't had a chance to dive deeper, but I am hoping to resolve soon.

**Comment by akhanf** [comment]
looks like it is in the `_get_file_paths` function that is incorrectly prefixing  self.snakemake_dir to the path.. will work on a fix, but in the meantime the quick fix to get hippunfold working again is to use `configfile_path='config/snakebids.yml'` when creating the app object in run.py

**Comment by pvandyken** [comment]
Ah, I can see the problem. Looks like the best solution would be to remove the self.snakemake_dir from _get_file_paths and adjust all references to configfile_path and snakefile_path accordingly.
