### ISSUE TITLE
bids() returning Path instead of str breaks workflows

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#119]
It looks like returning `Path` objects instead of `str` can break things in some workflows.

e.g. using snakemake's `multiext` with `bids()` as [here](https://github.com/akhanf/snakedwi/blob/eb124e6784ff08ca5190efc5aed185d9397903b9/snakedwi/workflow/rules/prepdwi.smk#L12) throws an error because it tries to join a Path and a str with `+`.
```
Traceback (most recent call last):
  File "/local/scratch/pypoetry_venv/snakebids-JiNcMeMJ-py3.8/lib/python3.8/site-packages/snakemake/__init__.py", line 593, in snakemake
    workflow.include(
  File "/local/scratch/pypoetry_venv/snakebids-JiNcMeMJ-py3.8/lib/python3.8/site-packages/snakemake/workflow.py", line 1186, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/local/scratch/snakedwi/snakedwi/workflow/Snakefile", line 65, in <module>
  File "/local/scratch/pypoetry_venv/snakebids-JiNcMeMJ-py3.8/lib/python3.8/site-packages/snakemake/workflow.py", line 1186, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/local/scratch/snakedwi/snakedwi/workflow/rules/prepdwi.smk", line 16, in <module>
    shell('cp -v {in_file} {out_file}')
  File "/local/scratch/pypoetry_venv/snakebids-JiNcMeMJ-py3.8/lib/python3.8/site-packages/snakemake/io.py", line 1192, in multiext
    return [flag(prefix + ext, "multiext", flag_value=prefix) for ext in extensions]
  File "/local/scratch/pypoetry_venv/snakebids-JiNcMeMJ-py3.8/lib/python3.8/site-packages/snakemake/io.py", line 1192, in <listcomp>
    return [flag(prefix + ext, "multiext", flag_value=prefix) for ext in extensions]
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

In hippunfold, things also get broken -- though I'm not exactly where it specifically breaks, as the failure manifests as a dag error in that workflow.  I suspect it may be related to rules like [this](https://github.com/khanlab/hippunfold/blob/a701848c2b066af8d21da53f936fb7fdef26e01a/hippunfold/workflow/rules/common.smk#L342)

```subject}_hemi-R_desc-unetf3d_dice.tsv']
Building DAG of jobs...
WorkflowError:
MissingInputException: Missing input files for rule copy_to_results:
results/work/sub-001/surf/sub-001_hemi-L_space-T2w_den-0p5mm_label-hipp_surfaces.spec
WorkflowError:
    MissingInputException: Missing input files for rule copy_to_results:
    results/work/sub-001/surf/sub-001_hemi-L_space-T2w_den-0p5mm_label-hipp_gyrification.shape.gii
    WorkflowError:
        MissingInputException: Missing input files for rule copy_to_results:
        results/work/sub-001/surf/sub-001_hemi-L_space-T2w_den-0p5mm_label-hipp_surfarea.shape.gii
        CyclicGraphException: Cyclic dependency on rule warp_gii_to_native.
```

@pvandyken do you have any objections to going back to have bids() ultimately cast to `str` when returning, so we can fix these issues? The issue with multiext seems to indicate snakemake maybe isn't completely compatible with Path objects.. Do you have any existing workflows or use-cases where bids() returning Path is needed?

**Comment by pvandyken** [comment]
That's annoying. My apologies, I made that change under the presumption that Snakemake fully supported Paths, but clearly did not do my due diligence checks. We can definitely revert it. 

It's something I'd still advocate for in the future, though with the realization now that it's a breaking change. I'm going to raise the `multiext` thing as an issue on Snakemake. I'm curious what's going on in the second error, although I can't makes heads or tails of it without the full context.

**Comment by akhanf** [comment]
Yea I see the benefit of having bids() return Path.. For the hippunfold workflow would take some digging through the rules to see how it is actually breaking..  once snakemake fully supports Path we can revive returning it in bids() and try to make our workflows compatible.

**Comment by pvandyken** [comment]
In hindsight it was definitely a naive decision to just switch the return type like that. My own workflows generally don't do complicated logic with paths, and when they do, I always convert to `Path()` anyway, but I wasn't thinking at all behind that. So I'll be sure to raise it as a discussion point next time first

**Comment by akhanf** [comment]
Would have caught this if I ran the PR with hippunfold or some other workflows initially -- wonder if we should add some test cases at some point that pull and dry-run some stable snakebids workflows? something to think about..
