### ISSUE TITLE
GH Bump Version + Branch Protection

### ISSUE THREAD

**Issue by kaitj** [akhanf/snakebids#144]
## The problem

It looks like PRs from forks aren't able to trigger the bump version correctly with the new GH action workflow + branch protection. @pvandyken noticed this last night when merging #143. 

A potential short-term solution (from the docs of the push action):

> If the PAT represents the repository owner, there are no issues, however, if the PAT represents a collaborator, the collaborator MUST be given the "Admin" role. This can be done under the "Settings" tab in the repository and then going to "Collaborators & teams". To understand what the "Admin" role allows the user to do, you can see the "Repository roles" page, which is also found under the "Settings" tab in the repository.

This however may still limit contributions from new users. Ideal solution would figure out a way around this. 

## Steps to reproduce

_From looking into the GH actions logs_

1. Fork repo
2. Make changes
3. Merge changes via PR

## Screenshots
Message about bad credentials
![image](https://user-images.githubusercontent.com/21226986/160240300-30188285-73ce-401b-b3d8-2c4045b28a44.png)

Last few merged PRs after branch protection was activated - only difference between passing and failing is merge came from a fork.
![image](https://user-images.githubusercontent.com/21226986/160240324-0cb3e488-9edc-42fa-8f14-56d70ab1fbb4.png)

## Environment

* Github actions

**Comment by kaitj** [comment]
Did some testing on my forked repo with trying to merge in a change from another user's fork. This is a similar issue we encountered with #132 and can be resolved by changing the actions trigger from `pull_request` to `pull_request_target`. In the other issue, we separated the reviewer assignment to another branch due to a potential vulnerability with the default github token + checking out the `main` branch (e.g. use the token to make direct changes to `main` via github API). 

Would have to weigh the pros and cons, but a solution could be:
* Change trigger to `pull_request_target`
* Disable admin(s) bypassing branch protection rules
* Disable force pushes

Any thoughts on this @tkkuehn @pvandyken @akhanf?

**Comment by pvandyken** [comment]
Can we disable force pushes just on the main branch? I use force pushes all the time on private side branches, but if we can just disable forces to main, it seems like that would solve many of the problems

**Comment by kaitj** [comment]
> Can we disable force pushes just on the main branch? I use force pushes all the time on private side branches, but if we can just disable forces to main, it seems like that would solve many of the problems

Believe that is part of the branch protection, which would only be active on the specified `main` branch.

**Comment by pvandyken** [comment]
Okay, so sorry, does that mean that you would be *allowed* to force push, or that only force pushes would be prohibited

**Comment by kaitj** [comment]
Force pushes would be prohibited on the main branch (in this repo) - should still work for other branches and forks

**Comment by akhanf** [comment]
happy to change the branch protection rules to make it work -- what should I exactly change here?

this is what we have right now: 
<img width="770" alt="image" src="https://user-images.githubusercontent.com/11492701/160425954-34fd2563-c68a-47bf-852e-8b9747bbff3d.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/11492701/160426135-e8e37513-43c6-4613-9b12-09d952632767.png">

**Comment by kaitj** [comment]
Ahh, yeah I couldn't remember what options were originally set. Don't think we would need to change anything then, just need to update the action to pull_request_target (will make a PR for this shortly).
