### ISSUE TITLE
Reviewers Being Reassigned after force push

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#148]
## The problem

@kaitj, I don't think this is a huge issue, really just a quality-of-life thing. Looks like right now when I make a force push on to an existing PR (especially after rebasing the branch onto new changes in `main`), GH refreshes all review requests (see the history of #138 for example). Is it possible and easy to set it so that only the initial pull request triggers the review request?

**Comment by kaitj** [comment]
Ahh, that is weird and thought I had copied this over directly from the `afids-validator`. I'll take a look make a PR for this if it is simple fix (hopefully later this week) that will check if the PR is already assigned, and if it is, it shouldn't add reviewers.
