### ISSUE TITLE
Cryptic error messages when pybids parsing fails

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#159]
The error is often something like:
```
AttributeError in line 13 of /usr/local/lib/python3.8/site-packages/funcmasker_flex/workflow/Snakefile:
'NoneType' object has no attribute 'get'
```

Would be good to catch these and try to provide a more specific error message about what happened.

**Comment by pvandyken** [comment]
The bids-inputs branch checks if `bids_layout is None`. Perhaps you could take a look and see if the current error msg covers your use-case?

**Comment by akhanf** [comment]
Re-opening this as I came across the issue again specifically when the dataset_description.json is missing or invalid.  Turns out this is an issue with pybids: https://github.com/bids-standard/pybids/issues/788

One workaround is to use `scope='all'` instead of `scope='raw'`, though not ideal..

**Comment by pvandyken** [comment]
A quick 'fix' would be to put pybids parsing inside a `try/except`, and carry forward any exceptions with a new exception saying that pybids encountered a problem. That at least puts the ball in pybid's court so that people know where to look for issues
