### ISSUE TITLE
Using '-' as bids_dir no longer acceptable

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#169]
## The problem

Previously we could set the bids dir to any string (e.g. `-`) if custom paths were specified with `--path-*` CLI options. 

With snakebids 0.6.0 this now gives an error, e.g. can be seen here:
https://github.com/khanlab/hippunfold/runs/6691842701?check_suite_focus=true

Since the workaround is pretty simple (just specify some folder as the bids dataset, or could be even `.`) not sure it is worth changing the behaviour so `-` would be acceptable, but interested in hearing what others think. It does feel odd to specify a folder when it is not being used at all though..

The downside of keeping things as is, is we would have to update documentation, tests, from other apps (e.g. hippunfold) that refer to using `-` as the input when solely custom paths are used.

**Comment by akhanf** [comment]
I like that idea

**Comment by pvandyken** [comment]
I figured out the underlying problem with this bug. When generating the `BidsLayout`, snakebids is supposed to check if the `bids_dir` passed `.exists()`. Instead, it's just checking if it's truthy:

```python
if Path(bids_dir):
   ...

# instead of
if Path(bids_dir).exists():
```

I'm still going to carry on with the idea above, though: I think the optimization is worth it, and it's fairly trivial to implement. But changing the above line, it's not strictly necessary anymore.
