### ISSUE TITLE
template project seems broken

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#170]
## The problem

Version 0.6.0 (and main branch) seems to have a broken project template. Does not happen in 0.5.1.

## Steps to reproduce
Creating a project with `snakebids create` (default options), and setting execute permission on run.py:
```
snakebids create
./my_bids_app/my_bids_app/run.py
chmod a+x ./my_bids_app/my_bids_app/run.py
```

Running the script gives this error:
```
(snakebids-JiNcMeMJ-py3.8) alik@AFI-CBS-H-17:/local/scratch/snakebids$ ./my_bids_app/my_bids_app/run.py
Traceback (most recent call last):
  File "./my_bids_app/my_bids_app/run.py", line 19, in <module>
    main()
  File "./my_bids_app/my_bids_app/run.py", line 14, in main
    app = SnakeBidsApp(Path(__file__).resolve().parent)  # to get repository root
  File "<attrs generated init snakebids.app.SnakeBidsApp>", line 9, in __init__
  File "/local/scratch/snakebids/snakebids/app.py", line 63, in wrapper
    raise ConfigError(
snakebids.exceptions.ConfigError
```

**Comment by akhanf** [comment]
ah it is because the workflow files are actually one directory higher.. 

The simple fix is easy (parent.parent), but not sure if we should keep the workflow files in the root folder for the snakebids template project.
I remember discussing placement of the workflow files, ie whether they are in the root folder (snakemake best practice) or the python package folder. 

I think what we found as a downside to having it in the root folder is the files end up in a weird location (above the package dir) when installed as a python package, so I have been putting the workflow files in the subfolder in my other projects (e.g. https://github.com/khanlab/funcmasker-flex). 

Anyone have any objections to this?

**Comment by tkkuehn** [comment]
Ah good catch. Seems fine/preferable to me to put the workflow files in the python package folder, as long as that folder then follows the Snakemake best practices.

**Comment by tkkuehn** [comment]
We now test the template project as part of our CI (See #151), so I think this can be closed.
