### ISSUE TITLE
More robust and generalizable BidsInputs

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#172]
*NOTE: below, I use datatype to refer to a specific set of filters and wildcards defined in the `pybids_inputs:` config entry in the `config.yml`. I realize datatype already has a specific meaning in BIDS, and welcome any suggestions for a better term.
***
The current `BidsInputs` is essentially a clone of the previous dict returned by `generate_inputs`, except that it uses attr access rather than item access for its members. This was fine for the first generation, but a few changes are possible for improvement:

### "Flipping" the class hierarchy
`BidsInputs` currently has `input_name`, `input_path` etc as the root level members, each of which in turn have the datatypes as item members. This requires a somewhat awkward implementation in the source code (e.g. `_BidsLists`, a named tuple, is used as an intermediary in class creation). It would be more natural to implement the reverse: to have the datatypes as the logical root level members, each of which contain `input_name`, `input_path`, etc as attr members.

To facilitate this, a new class, called here `BidsInput` would be defined. It would be very similar to the current `BidsInputs`, except that it would only contain data for one datatype. So `BidsInput.input_lists` instead of returning a dict (datatype) of dicts (entities) of lists (entity values), would return just a dict (entities) of lists (entity values).

The existing api would maintained: e.g. `BidsInputs.input_lists` would be turned into a property that iterates over all datatype members and grabs their `input_lists`, returning the familiar dict currently returned by `BidsInput.input_lists`. In addition to this api, however, item access directly on `BidsInputs` would also be possible. For instance, `BidsInputs["t1w"]` would return an instance of `BidsInput` specific to `"t1w"`.

Arguably, accessing inputs as e.g. `inputs["datatype"].input_path` is a more intuitive syntax, and I'd be open to documenting this syntax as the "proper" way to do it if others are interested.

### Defining attributes in terms of `input_zip_lists`

`input_zip_lists` is the fundamental attr in `BidsLists`, e.g. all other attrs can be calculated from it alone (excluding `input_path`, which is the other "fundamental attr"). Currently, `input_lists` and `input_wildcards` are calculated in `_get_lists_from_bids` and directly passed to the `BidsInputs` constructor. It would be more intuitive for their derivation code to be within `BidsInputs` as a `@property`. The value could be cached to save future compute time.

Aside from being more intuitive, this would make the maintenance of filtering code much simpler, as only `input_zip_lists` (and potentially `input_path`) would need to be modified.

### Changing the name of `BidsInputs`

As in the future we may want `BidsInputs` to encapsulate the names of derivative and output files, it may be prudent to change the name of `BidsInputs`. It seems the name should be either `Bids<x>s` or `<x>s`, where `<x>` is the term used to describe the "datatypes" defined under `pybids_inputs`. I've been calling them "datatypes" in this issue, but that term isn't great because "datatype" already has a bids-defined meaning. Suggestions would be appreciated.

**Comment by tkkuehn** [comment]
Thanks for this detailed writeup! This sounds great to me in principle, and I'll think about the naming and see if I can come up with any reasonable suggestions.

**Comment by pvandyken** [comment]
Just spent some time working up some possible names for the members of the `pybids_inputs`. Just to be clear, this would serve as the name describing the different "datatypes" (e.g. "t1w", "preproc_dwi", "bold", "mni_txf", etc) accessible currently via `BidsInputs`. It would also be the new name for both `BidsInputs` and the upcoming `BidsInput`.

Here's some candidates:
* item
* component
* constituent
* element
* feature
* member
* pathset/group
* category
* index
* entry
* group
* filegroup/set
* slice
* set
* files
* query

Of the list so far, I think I like component the best, although it's a little long (but no longer than datatype). But it feels natural (e.g. "the t1w component of the dataset").

Let me know if there's any other ideas/preferences (@akhanf, @tkkuehn, @kaitj)
