### ISSUE TITLE
Pretty Print version of BidsDataset

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#197]
## The problem

I'm wondering if it's worth having a pretty-printed version of BidsDataset to replicate the experience from before the `attrs` based class (pretty-printed dicts). Unfortunately, the native `pprint` module in python is not extensible (there's no `__pprint__` method we can just add to the class). However, ipython does offer an extensible, powerful (supports variable-width displays and recursion prevention) version of `pprint` within their built-ins, and it can be extended using the `_repr_pretty_` method. We could recast exploratory parts of the tutorial to use ipython, which would allow pretty printing of the datasets similar to before. 

Just to note an idea I've rejected: we could also change the `__str__` or `__repr__` methods, but both of these present problems. `__repr__` is meant for terse, unambiguous, programmatic representations of an object, not pretty printing. `__str__` is too broad: if you have `print(f"the inputs variable == {inputs}")`, do you really want a large, multi-line output here?

**Comment by tkkuehn** [comment]
I'm not opposed to customizing `__str__` for this (by analogy to how numpy arrays and pandas dataframes print), but there's not much of a downside to implementing `_repr_pretty_`, so that sounds good to me regardless.

**Comment by tkkuehn** [comment]
We confirmed to day that numpy arrays' `__str__` method includes newlines, so we can do that too.
