### ISSUE TITLE
pass helpful snakemake flags by default

### ISSUE THREAD

**Issue by jordandekraker** [akhanf/snakebids#2]
from https://github.com/khanlab/hippunfold/issues/12

eg.:
--keep-going
--keep-incomplete
cc-slurm profile

**Comment by akhanf** [comment]
The `--profile` option is going to be user-specific so wouldn't want to default for that, but as for the others I am not really keen on adding defaults here, since once it is added by default, there isn't a way a disable that option by command-line..
