### ISSUE TITLE
Saving more provenance information

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#205]
## The problem

This issue is somewhat relate to #182, but more specifically concerns what information is saved in the auto-generated `snakemake.yml` file. Currently we keep the entire config, any arguments passed to `run.py` (including snakemake args), and the snakemake and output directories. For full replicability, it would also be helpful to save the apṗ version (related to #85), and the snakemake version used to run the pipeline.

**Comment by akhanf** [comment]
I agree!

For the app version would we need to force users to expose the version in a particular way?

**Comment by pvandyken** [comment]
One more related thought: so long as we're reconstructing the config file from scratch, and given the order of attributes is arbitrary, it might be nice to purposefully organize things (and even put comments in if that can be managed... not sure) to make the file as human-readable as possible.

**Comment by akhanf** [comment]
yes a more human-readable config would be great!
