### ISSUE TITLE
Expose snakemake as a script

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#206]
## The problem

We currently have just `snakebids` exposed in the `pyproject.toml` file. If we also expose snakemake, this will be a small convenience for users installing snakebids via pipx. Currently you need to do:

```
pipx install snakemake
pipx inject snakemake snakebids --include-apps
```

With the change, you could do:

```
pipx install snakebids
```

And you'd get immediate access to both snakemake and snakebids.

There is a trade-off: upgrading snakemake is a bit more complicated:

```
pipx inject snakebids snakemake --pip-args --upgrade
```

However, this trade-off exists in the current situation, just in reverse. And this change wouldn't enforce a particular install pattern, just create the choice.

**Comment by akhanf** [comment]
This sounds like a good idea to me. Simplifying the install makes sense to me, even if upgrading becomes a little more complicated..

**Comment by tkkuehn** [comment]
We eventually want to lose the explicit dependency on Snakemake, so effort toward this would need to be reversed. For that reason, may as well close this.
