### ISSUE TITLE
Poetry Dynamic Versioning

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#207]
Just discovered this poetry plugin for [dynamic versioning](https://github.com/mtkennerly/poetry-dynamic-versioning). Basically it eliminates the need for any hardcoded versions in the source code, instead it infers the latest version from git tags. It integrates into poetry so that when you build, the correct version gets used.

The nice thing is that it automatically handles development states. So if there's not a version tag on the current release, it will take the last version tag found and add `.devX+hash` to make a unique version for every commit.

I think this is worth integrating into the project: it would greatly simplify our github actions, make our versioning even more fine-grained and precise, and eliminate those dedicated "version bump" commits, removing the problem we had with branch protection.

@kaitj, this overlaps with a lot of the work you did on the gh actions... any thoughts?

**Comment by kaitj** [comment]
Only had a chance to glance through the docs, but it is definitely interesting and worth a closer look at. I like the development states - it's a bit more definitive than what we currently have (e.g. `x.x.x-pre.1`). 

One initial thought is how does it determine the bumping (major vs minor vs patch) - just a thing to comb through their docs to figure out. It'd be nice to integrate this with the auto-release notes. The dedicated "version bump" commits were definitely a workaround so if this works, it'd definitely be cleaner.

**Comment by akhanf** [comment]
sounds like a good idea to me!
