### ISSUE TITLE
Intersection of bids_input lists, and subj_zip_list

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#208]
Was chatting about this the other day --
In workflows that make use of multiple bids inputs, it is often required to filter the subjects(+sessions) to only include those that are in all the inputs, that is, to perform an intersection of the input_zip_lists over all bids input types. E.g. to obtain subjects/session pairs where both T1w and dwi exist. 

In the longer-term, there are probably some more elegant solutions, but I would propose for the short-term to create a `subj_zip_list` variable that contains this.  

e.g. this is what I have added to my Snakefile to achieve this for the time being:  

 ```
subj_set_intersection = None
subj_zip_list = None

for bidsinput in config["pybids_inputs"].keys():
    zipl = inputs.input_zip_lists[bidsinput]
    if "session" in zipl:
        # has session, so we have to zip, then use set to remove duplicates
        subj_set = set(zip(zipl["subject"], zipl["session"]))
    else:
        # does not have session, so we can remove duplicates easily by using set
        subj_set = set(zipl["subject"])

    subj_set_intersection = (
        subj_set
        if subj_set_intersection == None
        else subj_set.intersection(subj_set_intersection)
    )

if "session" in zipl:
    (subzip, seszip) = zip(*list(subj_set_intersection))  # zip it up again
    subj_zip_list = {
        "subject": subzip,
        "session": seszip,
    }  # create the new subj_zip_list

else:
    subj_zip_list = {"subject": list(subj_set_intersection)}

```

Thoughts?

**Comment by pvandyken** [comment]
I'm not in principle opposed to a specific method like this, but it would be nice to have an idea for what the api will look like so we don't end up needing to walk back an enhancement. I'm going to start a dedicated discussion to try to start nailing something down

**Comment by pvandyken** [comment]
Closing, as this will be covered by the issues outlined in #209
