### ISSUE TITLE
Confusing Log message when no images found

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#215]
Got the following log message in my snakemake workflow:
```
No images found for participants
```

First, there's no indication this is a snakebids warning (to reiterate discussion in #184). If I wasn't a snakebids dev I doubt it would be obvious what had triggered the warning.

Second, I had to check the source code to realize that this was referring to the component I had, wisely or otherwise, called 'participants'. The remedy here is to add a lot more context to the error; something like:

```
No images found for the following components:
	participants:
		filters:
			blah
			blah
			blah
		wildcards:
			blah
			blah
```

**Comment by tkkuehn** [comment]
The line in question: https://github.com/akhanf/snakebids/blob/main/snakebids/core/input_generation.py#L962
