### ISSUE TITLE
integrate bids validator by default into snake bids

### ISSUE THREAD

**Issue by Remi-Gau** [akhanf/snakebids#222]
A lot of downstream errors can be prevented by early validation.

Would be useful to have an easy way for app creator to enforce validation.

Ideally it would make more sense to have validation be an opt out thing where app users have to add a `--skip-validation` flag.

For the moment this would only apply to raw datasets.

**Comment by pvandyken** [comment]
I believe this is easily implementable, we'd just transparently pass on a `validate` parameter from `generate_inputs` into `BIDSLayout`. The one gotcha would be that if all `custom_paths` are provided (after #224), no `BIDSLayout` would be generated so `validate` would be ignored. But if the user cared about a valid dataset, I don't think they'd be using all `custom_paths`.

**Comment by Remi-Gau** [comment]
Another option (not mutually exclusive) is to make a system call to the bids-validator (the in case the user user npm installed it.

Maybe first try the system call and if there is no bids-validator on the system then fall back to pybids validation (which I belive is just a call to the python "implementation" of the validator).

why am I suggesting a system call to the node.js validator?
it makes a lot more sense if you assume that people are going to use containerized bids apps rather than install snakebids generated apps with pip install.

**Comment by akhanf** [comment]
I'd also be in favour of having validation performed as the default, and skipped as an  option --  the app developer could always override this if it was exposed in generate_inputs.

**Comment by pvandyken** [comment]
@Remi-Gau, I'm not super familiar with either of the validators; what is the difference between the node version and python version? One of comprehensiveness?

**Comment by Remi-Gau** [comment]
yes exactly

the python version is not a very "deep" validation. Mostly that the filenames follow bids specification

the node/dyno versions go deeper and check json / tsv file content, nifti headers...
