### ISSUE TITLE
Extend boolean filtering to cli

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#258]
With #191, booleans can be used in the config file to filter for the presence or absence of entities. This capability was never extended into the cli.

There's a bit more ambiguity built in here: does `--filter-suchandsuch space=false` mean filter for spaces called `"false"`, or exclude `space` as an entity? I would lean toward the former and try to find an alternative syntax.

`False` can be expressed with a blank string: `--filter-suchandsuch space=`. `True` is a bit harder, but possibly an asterisk (like a bash wildcard?): `--filter-suchandsuch space='*'`?

**Comment by tkkuehn** [comment]
Proposal: `--filter-suchandsuch space.{required|optional|none}`
