### ISSUE TITLE
`--filter_{input_type}` ValueError

### ISSUE THREAD

**Issue by kaitj** [akhanf/snakebids#287]
## The problem

Encountered this one this morning while testing a workflow where `--filter-T1w` is used at the command-line. This was previously working in `0.7.2`, but no longer working as of `0.8.0`. Ended up getting the following error:

```python
Traceback (most recent call last):
  File "/project/6050199/tkai/shared_venvs/scattr-X3WkDvET-py3.9/bin/scattr", line 6, in <module>
    sys.exit(main())
  File "/scratch/tkai/0_dev/scattr/scattr/run.py", line 19, in main
    app.run_snakemake()
  File "/home/tkai/project/shared_venvs/scattr-X3WkDvET-py3.9/lib/python3.9/site-packages/snakebids/app.py", line 161, in run_snakemake
    update_config(self.config, args)
  File "/home/tkai/project/shared_venvs/scattr-X3WkDvET-py3.9/lib/python3.9/site-packages/snakebids/app.py", line 257, in update_config
    pybids_inputs[input_type]["filters"].update(arg_filter_dict)
ValueError: too many values to unpack (expected 2)
```

using the following call:

```bash
scattr /scratch/tkai/0_sandbox/scattr_test/bids /scratch/tkai/0_sandbox/scattr_test/derivatives participant --slurm_tmpdir --dwi_dir /scratch/tkai/0_sandbox/scattr_test/derivatives/prepdwi_v0.0.13/ --freesurfer_dir /scratch/tkai/0_sandbox/scattr_test/derivatives/fmriprep_v21.0.0_freesurfer/ --fs-license $FS_LICENSE_FILE --sl-count 5000 -p --cores 8 --use-singularity --bzero_thresh 15 --force-output --verbose --filter-T1w desc=synthstrip
```

I don't think we changed how the `update_config` call worked. May just be how I am calling it, but wanted to raise the issue in case it is something bigger.

## Steps to reproduce

* Run a workflow that uses snakebids `0.8.0` with `--filter-{input_type}` flag.

## Screenshots

If you have any helpful screenshots or a file you tried to upload, please include them!

## Environment

* `snakebids` version (if applicable): `0.8.0`
* Operating system (e.g. Ubuntu 20.04, Windows 10): Ubuntu 20.04

**Comment by pvandyken** [comment]
Probably a good time to handle #94, which is probably the reason this slipped past in the first place.

**Comment by pvandyken** [comment]
Just took a quick look and there's nothing obviously wrong with the code... if you're able to do a proper debug on your own setup, that would be great!

**Comment by pvandyken** [comment]
If we can at least patch up the bug for quick hotfix release, we can save more rigorous testing for later (but it definitely should be prioritized)

**Comment by kaitj** [comment]
> Just took a quick look and there's nothing obviously wrong with the code... if you're able to do a proper debug on your own setup, that would be great!

Yep, will take another look. I was looking through it this morning too and couldn't find anything immediately obvious.

> `arg_filter_dict` is not being treated like a dict here for some reason, I think the `ValueError` should only come up if it tries to treat an iterable as a key, value pair and it doesn't have enough elements

Throwing the above from a conversation with @tkkuehn this morning on Slack, which may be a place to start looking.

**Comment by kaitj** [comment]
Dug into it a little bit more with the workflow that was throwing this error. As @tkkuehn noted, it seems like the filtering is missing the value? The `arg_filter_dict` only returns the key, which is why I assume the `.update` call is failing. If I hardcode the update to what the key, value pair should be in the snakebids code (within the venv), the workflow (dry-)runs without issue.

![image](https://user-images.githubusercontent.com/21226986/235894995-f666efa9-fc2c-4b86-88e4-d3ad894d7a91.png)

So this may be stemming from how we are ultimately parsing and updating `snakebids_args.args_dict[f"filter_{input_type}"]`. That part of the code doens't look like its changed in 2 years though (at least in cli.py).
