### ISSUE TITLE
Update app creation instructions

### ISSUE THREAD

**Issue by kaitj** [akhanf/snakebids#307]
## The problem

After some discussion during the dev lunch, some things that would be helpful:
* Mentioning `pipx` installation of snakebids to be able to use `snakebids create`
* `snakebids create` is mentioned once in the documentation, but may want to make it more visible (maybe part of a quick start guide?)

~I noticed we have a cookiecutter template that is talked about in the documentation, but no actual instructions on how to use it to create a Snakebids project. This may be helpful for new users or those unfamiliar with cookiecutter. At the moment, one would need to call the following:~

~EDIT: Scratch most of this - after talking with Tristan, realized there is a `snakebids create` that is calling the cookiecuuter function. Still wonder about the possibility of splitting it off into its own repo.~

**Comment by pvandyken** [comment]
@kaitj, did you want to keep this open? Or can I close and just make a new issue when you have more details?

**Comment by kaitj** [comment]
I think it leave it open now, wanted to briefly discuss this at a dev lunch
