### ISSUE TITLE
add docstring documentation and doctest examples for each function

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#4]
A WIP example of this is here: https://github.com/akhanf/snakebids/blob/e8a89f125f9b029141cc4557af72fc7afa739048/snakebids/__init__.py#L161

**Comment by akhanf** [comment]
Adding doctests in #14, still a WIP

**Comment by akhanf** [comment]
I am thinking we can close this issue now too, what do you think @tkkuehn ?

**Comment by tkkuehn** [comment]
I think so! We don't necessarily have doctests for every function, but I think our test coverage and documentation are in pretty good shape.

**Comment by akhanf** [comment]
Great, will close this then
