### ISSUE TITLE
snakemake targets specified from command-line don't seem to be passed on to the app

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#48]
likely something introduced when I changed argument parsing, but the optional targets at the end of a command-line invocation don't seem to get passed along (ie the implicit target, specified in snakebids config `targets_by_analysis_level` always seems to override)

**Comment by tkkuehn** [comment]
I tried but wasn't able to reproduce this -- explicitly specified targets and rules both seem to work with Snakebids v0.3.10. I tried the app from the cookiecutter template with a few different targets and it seemed to react appropriately each time.

Explicit target:
```
$ ./demo_snakebids_app/demo_snakebids_app/run.py --participant_label=0003 \
> ../bids/ output/ participant --smoothing_fwhm 1 --cores --use-singularity \
> results/sub-0003/func/sub-0003_task-rest_run-01_desc-smooth1mm_bold.nii.gz
...
Job counts:
	count	jobs
	1	smooth
	1

[Thu Jun  3 16:40:47 2021]
rule smooth:
    input: /scratch/tkuehn/bids/sub-0003/func/sub-0003_task-rest_run-01_bold.nii.gz
    output: results/sub-0003/func/sub-0003_task-rest_run-01_desc-smooth1mm_bold.nii.gz
    log: logs/sub-0003/sub-0003_task-rest_run-01_fwhm-1_smooth.log
    jobid: 0
    wildcards: subject=0003, task=rest, run=01, fwhm=1
```

Explicit rule:
```
$ ./demo_snakebids_app/demo_snakebids_app/run.py --participant_label=0004 \
> ../bids/ output/ participant --smoothing_fwhm 1 --cores --use-singularity smooth

Building DAG of jobs...
WorkflowError:
Target rules may not contain wildcards. Please specify concrete files or a rule without wildcards.
```

Implicit target:
```
$ ./demo_snakebids_app/demo_snakebids_app/run.py --participant_label=0003 \
> ../bids/ output/ participant --smoothing_fwhm 1 --cores --use-singularity
...
Job counts:
	count	jobs
	1	all
	2	smooth
	3

[Thu Jun  3 16:50:55 2021]
rule smooth:
    input: /scratch/tkuehn/bids/sub-0003/func/sub-0003_task-movie_run-01_bold.nii.gz
    output: results/sub-0003/func/sub-0003_task-movie_run-01_desc-smooth1mm_bold.nii.gz
    log: logs/sub-0003/sub-0003_task-movie_run-01_fwhm-1_smooth.log
    jobid: 1
    wildcards: subject=0003, task=movie, run=01, fwhm=1
```

**Comment by akhanf** [comment]
I think this was related to having an explicit target rule in the config file, as when that exists, it always puts it on the command line. That's probably the expected behavior, and can be fixed by leaving `targets_by_analysis_level` as `''` to let snakemake implicitly find the first target rule. 

I'll make sure to update the template project to do this by default too.
