### ISSUE TITLE
Noncanonical use of __init__.py

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#62]
Snakebids currently uses `__init__.py` as the file holding the main body of code. Although other apps do this (notably, ahem, snakemake), this is a noncanonical way of using `__init__.py`, which should typically only be used as a way of organizing imports into the module namespace so that it's easier to import things. (e.g. so that users can simply do `from snakebids import x` rather than `from snakebids.file import x`).

As such, I'd like to move most of the code in that file to `main.py`. Is this alright with the other maintainers?

**Comment by akhanf** [comment]
Yes sounds good to me!

**Comment by akhanf** [comment]
Yep that works for me! I probably learned from that bad example!
