### ISSUE TITLE
Code Quality checks

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#63]
On implementing poetry, it would be good to agree on what formatters/quality checkers should be used in development. This would let us set up checks in gh-actions to ensure code quality. 

Currently we have:
- black
- pylint

Other possibilities:
- [isort](https://pypi.org/project/isort/) - Automatically organizes imports first by (stdlib, 3rd party, local) then by alphabet. I like it to keep things organized.
- [flake8](https://flake8.pycqa.org/en/latest/) - Stricter than black, but I don't think it does automatic formatting (so it's often combined with black). It depends how picky we want to be.

I'm also using [pre-commit](https://pre-commit.com/) in one of my other projects and find it quite useful. It basically just runs things like black, lint checks, etc on every commit. It's nice from a dev perspective because it can be set up with just one command, so you don't need to remember to do a bunch of checks every time you push. Happy to set it up for snakebids if we're interested.

**Comment by kaitj** [comment]
Most of my recent experience has been with `black`, though I have used `pylint` and `flake8` in the past. If I recall from past discussions, `black` doesn't fully follow PEP8, but is more user-readable. Any is fine with me as long as formatting is consistent across different contributions.

`isort` seems like a good thing to have. I also like to have the library imports organized, though I haven't used anything like this yet.

I would say the `pre-commit` is definitely nice to have, with a secondary check via `gh-actions`. In `gh-actions`, for security purposes, they don't allow commits to be pushed to forks (unless something has changed with the git tokens), which eliminates the automatic formatting in those cases. We have something similar setup for the afids-validator, with a pre-commit and a gh-actions.

**Comment by pvandyken** [comment]
Ya, I know when combining flake8 and black you need to make a few flake8 exceptions for them to be in agreement.

**Comment by akhanf** [comment]
Those suggestions sound good to me!

**Comment by tkkuehn** [comment]
I use pylint generally, and it is pretty picky but generally works well with black (I can't think of any conflicts off the top of my head).
