### ISSUE TITLE
SnakeBidsApp needs refactoring

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#81]
`SnakeBidsApp` in `app.py` is become quite long and convoluted. Attributes are defined across a number of functions, which rather confusing. And it breaks a few pylint rules (`too-many-instance-attributes`, `too-many-locals`) that would definitely simplify the class if fixed. So I plan on going through sometime soon and doing some refactoring.

**Comment by akhanf** [comment]
I agree, thanks for taking this on!
