### ISSUE TITLE
Function `run()` in `app.py`

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#82]
`run()` in `app.py` was previously used to call Snakemake in a subprocess. I've since changed that to directly call `Snakemake.main()`. The function is still used to call snakemake help, but that could also be updated to make a direct call to `main()`. Once done, is there any reason to keep the function? (Sort of an aside, but I *believe* the function's task can actually be achieved in just a few lines using `subprocess.open(...)`)

**Comment by akhanf** [comment]
Yes I think once it's changed over and unused can just remove the run function.
