### ISSUE TITLE
Warnings in `Pybids==0.14`

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#83]
Pybids v0.14 came out earlier this November ([CHANGELOG](https://bids-standard.github.io/pybids/whats_new.html). On running, a couple of warnings came up that should be corrected:
1. Looks like it finally supports the `GeneratedBy` field in the `dataset_description.json`, and comes with an upgrade script: `pybids upgrade`. So we can phase out efforts to support both; we'd just have to lock the `Pybids` version at 0.14.
  ```
  UserWarning: The PipelineDescription field was superseded by GeneratedBy in BIDS 1.4.0. You can use ``pybids upgrade`` to update your derivative dataset.
  ```
2. It's giving a deprecation warning about `extension_initial_dot` being phased out in v0.16. Sounds like `extension_initial_dot=True` is default in v0.14. So that'll be something to remove when switching to Pybids==0.14

If there's reason to not update the dependency to `v0.14` at this moment, should we restrict to `pybids==0.13` to prevent the warnings?
@akhanf @tkkuehn

**Comment by akhanf** [comment]
I think we can just move to 0.14 and remove the extraneous code. I've also been running 0.14 and haven't noticed any compatibility issues. I can start a PR for this at some point today.
